builds:
  - binary: onigiri
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
replacements:
  amd64: 64-bit
  386: 32-bit
  darwin: macOS
checksum: false
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: omi-chan
    name: onigiri-catch